[package]
name = "btw"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = "line-tables-only"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
anyhow = "1.0.95"
reqwest = { version = "0.12.9", features = ["json", "rustls-tls"], default-features = false }
serenity = { version = "0.12.4", features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
url = "2.5.4"
