name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set data for subsequent steps
        id: data
        run: |
          VERSION="$(nix eval --raw -- .#metadata.cargo.package.version)"
          echo "image=registry.fly.io/btw:$VERSION-glibc" >> $GITHUB_OUTPUT
      - name: Cache built dependency crates
        uses: ./.github/actions/cache
        with:
          package: .#_deps
      - name: Cache built image
        uses: ./.github/actions/cache
        with:
          package: .#image-glibc
      - run: nix build .#image-glibc
      - name: Push image to Fly.io registry
        # --insecure-policy:
        #   Don't look for `policy.json` file in local filesystem
        run: >
          nix run --inputs-from . nixpkgs#skopeo --
          --insecure-policy
          copy
          --format v2s2
          --dest-creds x:${{ secrets.FLY_ACCESS_TOKEN }}
          -- docker-archive:result
          docker://${{ steps.data.outputs.image }}
      - name: Deploy image from Fly.io registry
        run: >
          nix run --inputs-from . nixpkgs#flyctl --
          deploy
          --remote-only
          --image ${{ steps.data.outputs.image }}
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
