name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build image
        run: nix build .#container
      - name: Push image
        run: |
          nix run nixpkgs#skopeo --inputs-from . -- copy --debug \
            --format v2s2 \
            --dest-creds x:${{ secrets.FLY_API_TOKEN }} \
            docker-archive:"$(readlink ./result)" \
            docker://registry.fly.io/btw:latest
      - name: Deploy image
        run: flyctl deploy --image registry.fly.io/btw:latest --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
