name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build image
        run: nix build .#container-glibc
      - name: Push image to Fly.io registry
        run: |
          VERSION=$(nix eval .#metadata.package.version)
          # Remove double quotes from `$VERSION` string
          VERSION=${VERSION//\"/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          # --debug: Enable verbose output
          # --insecure-policy: Don't look for `policy.json` file in local filesystem
          nix run nixpkgs#skopeo --inputs-from . -- --debug --insecure-policy copy \
            --format v2s2 \
            --dest-creds x:${{ secrets.FLY_ACCESS_TOKEN }} \
            docker-archive:result \
            docker://registry.fly.io/btw:${VERSION}-glibc
      - name: Deploy image from Fly.io registry
        run: |
          nix run nixpkgs#flyctl --inputs-from . -- deploy --remote-only \
            --image registry.fly.io/btw:${{ env.VERSION }}-glibc
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
