name: Deploy

on:
  push:
    branches:
      - main
      - test/deploy

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Login to registry.fly.io
        uses: docker/login-action@v3
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}
      - name: Install pkg-config
        run: sudo apt update && sudo apt install -y pkg-config libssl-dev
      - name: Build image
        run: nix build .#container
      - name: Push image
        run: |
          SRC_PATH=$(readlink ./result)
          nix run nixpkgs#skopeo -- copy --debug \
            --format v2s2 \
            docker-archive:"$SRC_PATH" \
            docker://registry.fly.io/btw:latest
      - name: Deploy
        run: flyctl deploy --image registry.fly.io/btw:latest --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
