name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      # https://determinate.systems/posts/magic-nix-cache-free-tier-eol/
      # - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix build .#image-glibc
      - name: Push image to Fly.io registry
        run: |
          VERSION=$(nix eval .#metadata.cargo.package.version --raw)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          # --debug: Enable verbose output
          # --insecure-policy: Don't look for `policy.json` file in local filesystem
          nix run nixpkgs#skopeo --inputs-from . -- --debug --insecure-policy copy \
            --format v2s2 \
            --dest-creds x:${{ secrets.FLY_ACCESS_TOKEN }} \
            docker-archive:result \
            docker://registry.fly.io/btw:${VERSION}-glibc
      - name: Deploy image from Fly.io registry
        run: |
          nix run nixpkgs#flyctl --inputs-from . -- deploy --remote-only \
            --image registry.fly.io/btw:${{ env.VERSION }}-glibc
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
